"""Rendering scan results to CSV, TXT and JSON.

A long list is segmented into numbered CSV parts inside a per-export folder, so
a scan of tens of thousands of members stays openable in a spreadsheet instead
of producing one file nothing will load.

Whatever is written carries the attribution line Rotector's Terms of Use ask
for, and says what its own retention is: the 24-hour expiry the terms set, or
-- when the operator has switched ``scan.retain_beyond_terms`` on -- how long
this file is actually being kept, and that the terms allow 24. The reader of an
exported file did not make that choice and is entitled to know which of the two
they are holding, and to see any finding in it that is already older than the
window labelled as stale.
"""

from __future__ import annotations

import csv
import json
import shutil
from collections.abc import Callable, Iterable, Sequence
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from pathlib import Path

from .rotector import (
    MemberReport,
    describe_age,
    is_stale,
    report_age,
    stale_note,
)
from .verdict import (
    ATTRIBUTION,
    category_name,
    flag_is_actionable,
    flag_name,
    source_names,
    verdict_label,
)

#: rows per CSV segment when segmentation is on
DEFAULT_SEGMENT_SIZE = 1000

#: line written into every export's README, and the marker that makes a folder
#: safe to delete -- nothing without it is ever touched
MARKER = "Generated by rotector-selfbot. Safe to delete."

#: Rotector's Terms of Use forbid retaining responses beyond this
RETENTION_HOURS = 24


@dataclass
class ExportRow:
    """One member, paired with whatever the UI knows about them."""

    discord_id: str
    username: str
    display_name: str
    report: MemberReport


# --------------------------------------------------------------------------
# columns
# --------------------------------------------------------------------------


def _worst(row: ExportRow):
    return row.report.worst_account


COLUMNS: dict[str, Callable[[ExportRow], str]] = {
    "discord_id": lambda r: r.discord_id,
    "username": lambda r: r.username,
    "display_name": lambda r: r.display_name,
    "verdict": lambda r: verdict_label(r.report.verdict),
    # Empty for a finding inside the window, so the column costs nothing to
    # read in the ordinary case and cannot be mistaken for a verdict of its
    # own. A value here means the row is a claim about a day or more ago.
    "stale": lambda r: (
        f"{describe_age(report_age(r.report))} old"
        if is_stale(r.report)
        else ""
    ),
    "flag": lambda r: flag_name(_worst(r).flag_type if _worst(r) else None),
    "actionable": lambda r: str(
        flag_is_actionable(_worst(r).flag_type if _worst(r) else None)
    ).lower(),
    "category": lambda r: category_name(_worst(r).category if _worst(r) else None) or "",
    "confidence": lambda r: (
        f"{_worst(r).confidence:.2f}"
        if _worst(r) and _worst(r).confidence is not None
        else ""
    ),
    "roblox_accounts": lambda r: " ".join(
        f"{a.username}({a.user_id})" for a in r.report.accounts
    ),
    "roblox_ids": lambda r: " ".join(str(a.user_id) for a in r.report.accounts),
    "roblox_profiles": lambda r: " ".join(a.profile_url for a in r.report.accounts),
    "detection_sources": lambda r: " ".join(
        source_names(a.sources) for a in r.report.accounts
    ),
    "tracked_servers": lambda r: str(len(r.report.servers)),
    "tracked_server_names": lambda r: " | ".join(
        s.server_name for s in r.report.servers
    ),
    "reasons": lambda r: " | ".join(
        f"{name}: {str(detail.get('message', '')).replace(chr(10), ' / ')}"
        for account in r.report.accounts
        for name, detail in (account.reasons or {}).items()
    ),
    "evidence": lambda r: " | ".join(
        str(item)
        for account in r.report.accounts
        for detail in (account.reasons or {}).values()
        for item in (detail.get("evidence") or [])
    ),
    "error": lambda r: r.report.error or "",
}

#: sensible default column set
DEFAULT_COLUMNS = [
    "discord_id",
    "username",
    "display_name",
    "verdict",
    # on by default, because a stale finding that is not labelled reads as a
    # current one, and the column is blank for every finding inside the window
    "stale",
    "flag",
    "actionable",
    "category",
    "confidence",
    "roblox_accounts",
    "tracked_servers",
    "reasons",
]

ALL_COLUMNS = list(COLUMNS)


def valid_columns(names: Iterable[str]) -> list[str]:
    """Keep only columns that exist, preserving the caller's order."""
    seen, out = set(), []
    for name in names:
        if name in COLUMNS and name not in seen:
            seen.add(name)
            out.append(name)
    return out or list(DEFAULT_COLUMNS)


# --------------------------------------------------------------------------
# manifest
# --------------------------------------------------------------------------


@dataclass
class ExportManifest:
    directory: Path
    files: list[Path]
    rows: int
    segments: int
    formats: list[str]
    scope: str
    purged: list[Path] = field(default_factory=list)

    def describe(self) -> str:
        parts = f"{self.segments} segments" if self.segments > 1 else "1 file"
        return (
            f"{self.rows:,} rows -> {len(self.files)} file(s) ({parts}) "
            f"in {self.directory}"
        )


def _parse_stamp(stamp: str) -> datetime | None:
    try:
        return datetime.strptime(stamp, "%Y%m%dT%H%M%SZ").replace(tzinfo=timezone.utc)
    except ValueError:
        return None


def _stamp_from_name(name: str) -> datetime | None:
    """Recover the timestamp a folder was written with, from its name."""
    tail = name.rsplit("-", 1)[-1]
    return _parse_stamp(tail)


def purge_expired(
    base_directory: Path,
    max_age_hours: int = RETENTION_HOURS,
    now: datetime | None = None,
) -> list[Path]:
    """Delete exports past their retention window.

    Deliberately conservative, because this removes files. A folder is only
    ever considered if it sits directly under ``base_directory``, its name
    carries a timestamp we wrote, and it contains a README bearing our marker.
    Anything else -- a folder the user made, an unrelated directory that
    happens to be there -- is left alone no matter how old it is.
    """
    base = Path(base_directory)
    if not base.is_dir():
        return []

    now = now or datetime.now(timezone.utc)
    cutoff = now - timedelta(hours=max_age_hours)
    removed: list[Path] = []

    for entry in sorted(base.iterdir()):
        if not entry.is_dir() or entry.is_symlink():
            continue
        stamp = _stamp_from_name(entry.name)
        if stamp is None or stamp > cutoff:
            continue
        readme = entry / "README.txt"
        try:
            if not readme.is_file() or MARKER not in readme.read_text(encoding="utf-8"):
                continue
        except OSError:
            continue
        try:
            shutil.rmtree(entry)
        except OSError:
            continue
        removed.append(entry)
    return removed


def count_stale(rows: Sequence[ExportRow]) -> int:
    """How many of these findings are already past the 24-hour window.

    Independent of any setting: results left on screen for two days are just as
    stale as ones served from a cache that was told to keep them, and a file is
    entitled to say so either way.
    """
    return sum(1 for row in rows if is_stale(row.report))


def _header_lines(
    guild_name: str,
    stamp: str,
    scope: str,
    rows: int,
    *,
    retain_beyond_terms: bool = False,
    retention_hours: int = RETENTION_HOURS,
    stale: int = 0,
) -> list[str]:
    """The block every text-shaped export opens with.

    The expiry line states what is true of *this* file. When retention past the
    terms has been switched on, repeating "delete within 24 hours" would be
    describing a rule the run did not follow, so the line says how long the file
    is being kept and what the terms allow instead -- and still names them,
    because whoever opens the file did not make that choice.
    """
    generated = datetime.strptime(stamp, "%Y%m%dT%H%M%SZ").replace(
        tzinfo=timezone.utc
    )
    hours = retention_hours if retain_beyond_terms else RETENTION_HOURS
    expires = (generated + timedelta(hours=hours)).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        f"Server:    {guild_name}",
        f"Generated: {stamp}",
        f"Scope:     {scope}",
        f"Members:   {rows}",
    ]
    if retain_beyond_terms:
        lines.append(
            f"Expires:   {expires} - kept {hours}h by the operator's choice; "
            f"Rotector's Terms of Use allow {RETENTION_HOURS}h"
        )
    else:
        lines.append(
            f"Expires:   {expires} - Rotector Terms of Use forbid keeping this longer"
        )
    if stale:
        lines.append(
            f"Stale:     {stale} of {rows} finding(s) are already older than "
            f"{RETENTION_HOURS} hours - see the Stale column, and re-check "
            f"before acting"
        )
    lines.append(f"Source:    {ATTRIBUTION}")
    return lines


# --------------------------------------------------------------------------
# renderers
# --------------------------------------------------------------------------


def render_csv(
    rows: Sequence[ExportRow],
    directory: Path,
    stem: str,
    columns: Sequence[str],
    segment_size: int = DEFAULT_SEGMENT_SIZE,
) -> list[Path]:
    """Write CSV, split into numbered segments when the list is long.

    ``segment_size`` of 0 (or a list shorter than one segment) produces a
    single file; otherwise each part is a complete CSV with its own header, so
    every segment opens on its own.
    """
    columns = valid_columns(columns)
    written: list[Path] = []

    if segment_size and len(rows) > segment_size:
        chunks = [
            rows[i : i + segment_size] for i in range(0, len(rows), segment_size)
        ]
    else:
        chunks = [list(rows)]

    width = len(str(len(chunks)))
    for index, chunk in enumerate(chunks, start=1):
        name = (
            f"{stem}.csv"
            if len(chunks) == 1
            else f"{stem}.part{index:0{width}d}-of-{len(chunks)}.csv"
        )
        path = directory / name
        with path.open("w", newline="", encoding="utf-8") as handle:
            writer = csv.writer(handle)
            writer.writerow(columns)
            for row in chunk:
                writer.writerow([COLUMNS[column](row) for column in columns])
        written.append(path)
    return written


def render_txt(
    rows: Sequence[ExportRow],
    directory: Path,
    stem: str,
    columns: Sequence[str],
    guild_name: str,
    stamp: str,
    scope: str,
    retain_beyond_terms: bool = False,
    retention_hours: int = RETENTION_HOURS,
) -> list[Path]:
    """A readable report -- one block per member, not a table."""
    columns = valid_columns(columns)
    path = directory / f"{stem}.txt"
    labels = {c: c.replace("_", " ").title() for c in columns}
    pad = max((len(l) for l in labels.values()), default=0)

    lines: list[str] = []
    header = _header_lines(
        guild_name,
        stamp,
        scope,
        len(rows),
        retain_beyond_terms=retain_beyond_terms,
        retention_hours=retention_hours,
        stale=count_stale(rows),
    )
    rule = "=" * max(len(h) for h in header)
    lines.append(rule)
    lines.extend(header)
    lines.append(rule)
    lines.append("")

    for index, row in enumerate(rows, start=1):
        title = f"{index}. {row.display_name}"
        if row.username and row.username != row.display_name:
            title += f" (@{row.username})"
        lines.append(title)
        lines.append("-" * len(title))
        # Spelled out per member rather than left to the Stale column, which the
        # operator can deselect: whether this line is a claim about today is not
        # a formatting preference.
        if note := stale_note(row.report):
            lines.append(f"  {note}")
        for column in columns:
            value = COLUMNS[column](row)
            if not value:
                continue
            lines.append(f"  {labels[column]:<{pad}}  {value}")
        lines.append("")

    if not rows:
        lines.append("(no members matched the selected filter)")
        lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")
    return [path]


def render_json(
    rows: Sequence[ExportRow],
    directory: Path,
    stem: str,
    columns: Sequence[str],
    guild_name: str,
    guild_id: str,
    stamp: str,
    scope: str,
    retain_beyond_terms: bool = False,
    retention_hours: int = RETENTION_HOURS,
) -> list[Path]:
    columns = valid_columns(columns)
    path = directory / f"{stem}.json"
    stale = count_stale(rows)
    payload = {
        "guild": {"id": guild_id, "name": guild_name},
        "generated_at": stamp,
        "scope": scope,
        # What is true of this file, not the rule in the abstract: repeating the
        # 24-hour line over data deliberately kept longer would be a claim the
        # run did not honour. The terms are named either way.
        "expires_at": (
            f"{retention_hours} hours after generated_at - kept past the 24 hours "
            "Rotector's Terms of Use #1 allow, by the operator's choice"
            if retain_beyond_terms
            else "24 hours after generated_at (Rotector Terms of Use #1)"
        ),
        "retained_beyond_terms": bool(retain_beyond_terms),
        "stale_findings": stale,
        "stale_note": (
            f"{stale} finding(s) here are older than 24 hours. Flag types change "
            "and appeals succeed, so those describe the day they were answered, "
            "not today - re-check before acting. Per-member ages are in the "
            "'stale' column."
            if stale
            else ""
        ),
        "attribution": ATTRIBUTION,
        "columns": list(columns),
        "members": [
            {column: COLUMNS[column](row) for column in columns} for row in rows
        ],
    }
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    return [path]


# --------------------------------------------------------------------------


def export(
    rows: Sequence[ExportRow],
    *,
    guild_name: str,
    guild_id: str,
    base_directory: Path,
    formats: Sequence[str],
    columns: Sequence[str],
    scope: str = "filtered",
    segment_size: int = DEFAULT_SEGMENT_SIZE,
    stamp: str | None = None,
    preserve: bool = False,
    retain_beyond_terms: bool = False,
    retention_hours: int = RETENTION_HOURS,
    png_style: str = "table",
    profiles: dict | None = None,
    palette=None,
) -> ExportManifest:
    """Render ``rows`` into a dedicated folder and describe what was written."""
    stamp = stamp or datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    base_directory = Path(base_directory)
    base_directory.mkdir(parents=True, exist_ok=True)

    # Housekeeping first, so a new export never sweeps away its own folder. The
    # sweeper honours whichever window this run is actually claiming: with
    # retention past the terms switched on, clearing folders at 24 hours anyway
    # would delete files whose own README says they are kept longer.
    sweep_after = retention_hours if retain_beyond_terms else RETENTION_HOURS
    purged = [] if preserve else purge_expired(base_directory, sweep_after)
    safe = "".join(c if c.isalnum() or c in "-_" else "-" for c in guild_name)[:40]
    stem = f"{safe}-{stamp}"
    directory = Path(base_directory) / stem
    directory.mkdir(parents=True, exist_ok=True)

    formats = [f.lower() for f in formats] or ["csv"]
    columns = valid_columns(columns)
    files: list[Path] = []
    segments = 1

    if "csv" in formats:
        csv_files = render_csv(rows, directory, stem, columns, segment_size)
        segments = len(csv_files)
        files += csv_files
    if "txt" in formats:
        files += render_txt(
            rows, directory, stem, columns, guild_name, stamp, scope,
            retain_beyond_terms=retain_beyond_terms,
            retention_hours=retention_hours,
        )
    if "json" in formats:
        files += render_json(
            rows, directory, stem, columns, guild_name, guild_id, stamp, scope,
            retain_beyond_terms=retain_beyond_terms,
            retention_hours=retention_hours,
        )
    if "png" in formats:
        from .imagerender import available as png_available, render_png

        if png_available():
            images = directory / "png"
            images.mkdir(exist_ok=True)
            files += render_png(
                rows,
                images,
                stem,
                columns,
                title=guild_name,
                subtitle=f"{scope}  -  generated {stamp}",
                style=png_style,
                profiles=profiles,
                palette=palette,
                retain_beyond_terms=retain_beyond_terms,
                retention_hours=retention_hours,
            )
        else:
            formats = [f for f in formats if f != "png"]
    if "html" in formats:
        from .htmlrender import render_html

        pages = directory / "html"
        pages.mkdir(exist_ok=True)
        files += render_html(
            rows,
            pages,
            stem,
            columns,
            guild_name=guild_name,
            stamp=stamp,
            scope=scope,
            profiles=profiles,
            palette=palette,
            retain_beyond_terms=retain_beyond_terms,
            retention_hours=retention_hours,
        )

    relative = [
        f.relative_to(directory) if f.is_relative_to(directory) else f for f in files
    ]
    stale = count_stale(rows)
    if retain_beyond_terms:
        # Not "delete within 24 hours": this run was told to keep the data
        # longer, and printing the rule it did not follow would be theatre. The
        # terms are still named, and so is what that means for the findings.
        retention_note = [
            f"This export is being kept for {retention_hours} hours by choice.",
            f"Rotector's Terms of Use allow {RETENTION_HOURS} hours, and flag",
            "statuses change well inside that: anything here older than a day",
            "describes the day it was answered rather than today. Anyone listed",
            "can appeal at https://rotector.com",
        ]
    else:
        retention_note = [
            f"Delete this folder within {RETENTION_HOURS} hours. Rotector flag",
            "statuses change, and their Terms of Use forbid retaining responses",
            "beyond that. Anyone listed here can appeal at https://rotector.com",
        ]
    if stale:
        retention_note += [
            "",
            f"{stale} of the {len(rows)} finding(s) here were already older than "
            f"{RETENTION_HOURS} hours",
            "when this was written; each one's age is in the Stale column. Re-check "
            "before acting on those.",
        ]

    readme = directory / "README.txt"
    readme.write_text(
        "\n".join(
            [
                *_header_lines(
                    guild_name,
                    stamp,
                    scope,
                    len(rows),
                    retain_beyond_terms=retain_beyond_terms,
                    retention_hours=retention_hours,
                    stale=stale,
                ),
                "",
                "Files:",
                *(f"  {f}" for f in relative),
                "",
                *retention_note,
                "",
                MARKER,
            ]
        )
        + "\n",
        encoding="utf-8",
    )
    files.append(readme)

    return ExportManifest(
        directory=directory,
        files=files,
        rows=len(rows),
        segments=segments,
        formats=list(formats),
        scope=scope,
        purged=purged,
    )
