/*
 * RotectorScan — a Discord-client port of rotector-selfbot
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * Rendering scan results to files, and handing them to the user.
 *
 * A port of rsb/export.py, which has the shape it does because of two of
 * Rotector's Terms of Use rather than because of taste:
 *
 *  - Every file carries the attribution line, so that a finding pasted into a
 *    ticket still says where it came from and who to appeal to.
 *  - Every file states its expiry, because the terms forbid retaining their
 *    responses beyond 24 hours. The terminal app can enforce that itself
 *    (`purge_expired` deletes its own folders); a browser cannot delete a file
 *    it handed to the download manager, so the *statement* is the only
 *    enforcement left and it is therefore not optional anywhere.
 *
 * When `retainBeyondTerms` is on, that statement says how long this file is
 * actually being kept and that the terms allow 24 hours — rather than repeating
 * a rule the run did not follow. Whoever opens the file did not make that
 * choice and is entitled to know which of the two they are holding, and to see
 * any finding in it that was already past the window labelled as stale. The
 * `stale` column and `staleNote` do that per row, whichever way the setting is
 * set: results left on screen for two days go stale by themselves.
 *
 * A long list segments into numbered CSV parts for the same reason it does in
 * the Python: a scan of tens of thousands of members produces one file nothing
 * will open, and a moderator who cannot open the export has no export.
 *
 * rsb/palette.py sits under this module rather than beside it — the HTML and
 * the PNG renderers both take their colours from here, so "match the app's
 * theme" stays one decision instead of two that can disagree.
 */

import { Logger } from "@utils/Logger";
import { IconUtils, UserStore } from "@webpack/common";

import { retainBeyondTermsFrom, retentionHoursFrom } from "../api/backend";
import {
    describeAge,
    isStale,
    MemberReport,
    profileUrl,
    reportAge,
    reportVerdict,
    sortedAccounts,
    staleNote,
    worstAccount,
} from "../api/types";
import {
    ALL_VERDICTS,
    ATTRIBUTION,
    categoryName,
    flagIsActionable,
    flagName,
    sourceNames,
    Verdict,
    verdictLabel,
    verdictMeaning,
    verdictName,
} from "../api/verdict";
import { settings } from "../settings";

const logger = new Logger("RotectorScan");

/** rows per CSV segment when segmentation is on (rsb/export.py:33) */
export const DEFAULT_SEGMENT_SIZE = 1000;

/**
 * Rotector's Terms of Use forbid retaining responses beyond this.
 *
 * Still a constant, and still the number every file names, because it is the
 * rule rather than a setting: `retainBeyondTerms` changes how long this plugin
 * keeps a finding, never how long the terms allow one to be kept. A file kept
 * longer says so *and* prints this figure, so its reader learns both.
 */
export const RETENTION_HOURS = 24;

/** the line the Python writes into every export's README, kept for continuity */
export const MARKER = "Generated by rotector-selfbot (RotectorScan plugin). Safe to delete.";

export const APPEAL_URL = "https://rotector.com";

export type ExportFormat = "csv" | "txt" | "html" | "png" | "json";

/** the formats in the order the menu offers them */
export const EXPORT_FORMATS: ExportFormat[] = ["csv", "txt", "json", "html", "png"];

// --------------------------------------------------------------------------
// rows
// --------------------------------------------------------------------------

/**
 * One member, paired with whatever the client knows about them.
 *
 * The Python builds these in the TUI, where the username is already to hand.
 * Here the report is all a caller has, so `buildRows` fills the rest from
 * UserStore — and tolerates it being empty, because a scan can list somebody
 * who has since left and whom the client no longer holds.
 */
export interface ExportRow {
    discordId: string;
    username: string;
    displayName: string;
    /** the client's own avatar URL, used by the HTML cards; never fetched here */
    avatarUrl: string | null;
    report: MemberReport;
}

/** Reports, or rows already built from them. Both are accepted everywhere. */
export type ExportInput = MemberReport[] | ExportRow[];

function safely<T>(fn: () => T, fallback: T): T {
    try {
        const value = fn();
        return value === undefined || value === null ? fallback : value;
    } catch {
        return fallback;
    }
}

function readUser(id: string): any {
    return safely(() => (UserStore as any)?.getUser?.(id) ?? null, null);
}

function avatarFor(user: any): string | null {
    if (!user) return null;
    return safely(() => {
        const url = (IconUtils as any)?.getUserAvatarURL?.(user, false, 128);
        if (url) return url;
        return (IconUtils as any)?.getDefaultAvatarURL?.(user.id, user.discriminator) ?? null;
    }, null);
}

/** One report, as a row. Unknown members keep their id, which is what identifies them. */
export function buildRow(report: MemberReport): ExportRow {
    const id = String(report?.discordId ?? "");
    const user = readUser(id);
    const username = String(user?.username ?? "");
    const displayName = String(user?.globalName || user?.username || (id ? `Unknown member ${id}` : "Unknown member"));
    return {
        discordId: id,
        username,
        displayName,
        avatarUrl: avatarFor(user),
        report: report ?? ({ discordId: id, accounts: [], servers: [], signals: [], error: null, fetchedAt: Date.now() } as any),
    };
}

export function buildRows(reports: MemberReport[]): ExportRow[] {
    if (!Array.isArray(reports)) return [];
    return reports.filter(Boolean).map(buildRow);
}

/** Whatever the caller handed us, as rows. */
export function asRows(input: ExportInput | null | undefined): ExportRow[] {
    if (!Array.isArray(input)) return [];
    const out: ExportRow[] = [];
    for (const entry of input as any[]) {
        if (!entry) continue;
        if (entry.report && typeof entry.discordId === "string") {
            out.push(entry as ExportRow);
        } else {
            out.push(buildRow(entry as MemberReport));
        }
    }
    return out;
}

// --------------------------------------------------------------------------
// columns — the same set, in the same order, as rsb/export.py:62-118
// --------------------------------------------------------------------------

function worst(row: ExportRow) {
    return safely(() => worstAccount(row.report), null);
}

function rowVerdict(row: ExportRow): Verdict {
    return safely(() => reportVerdict(row.report), Verdict.UNKNOWN);
}

function accountsOf(row: ExportRow) {
    return safely(() => sortedAccounts(row.report), [] as ReturnType<typeof sortedAccounts>);
}

function flat(value: unknown): string {
    return String(value ?? "").replace(/[\r\n]+/g, " / ").trim();
}

export const COLUMNS: Record<string, (row: ExportRow) => string> = {
    discord_id: r => r.discordId,
    username: r => r.username,
    display_name: r => r.displayName,
    verdict: r => verdictLabel(rowVerdict(r)),
    /**
     * The meaning, beside the word.
     *
     * Not in the Python's column set, and offered here because the plugin's own
     * rule is stricter than the file format: NO DETECTIONS may never be read as
     * "safe", and a bare column of verdict words in a spreadsheet is exactly
     * where that misreading happens. It is not in DEFAULT_COLUMNS — every file
     * already prints the legend in its header — but it is available for anyone
     * who wants the sentence on the row itself.
     */
    verdict_meaning: r => verdictMeaning(rowVerdict(r)),
    /**
     * How old this answer is, when it is older than the terms' window.
     *
     * Empty for a finding inside the window, so the column costs nothing to
     * read in the ordinary case and cannot be mistaken for a verdict of its
     * own. A value here means the row is a claim about a day or more ago —
     * flag types change and appeals succeed, so the reader is owed that before
     * they act on it. rsb/export.py:80 writes the same cell.
     */
    stale: r => (isStale(r.report) ? `${describeAge(reportAge(r.report))} old` : ""),
    flag: r => flagName(worst(r)?.flagType ?? null),
    actionable: r => String(flagIsActionable(worst(r)?.flagType ?? null)),
    category: r => categoryName(worst(r)?.category ?? null) ?? "",
    confidence: r => {
        const c = worst(r)?.confidence;
        return typeof c === "number" && isFinite(c) ? c.toFixed(2) : "";
    },
    roblox_accounts: r => accountsOf(r).map(a => `${a.username}(${a.userId})`).join(" "),
    roblox_ids: r => accountsOf(r).map(a => String(a.userId)).join(" "),
    roblox_profiles: r => accountsOf(r).map(a => safely(() => profileUrl(a), "")).join(" "),
    detection_sources: r => accountsOf(r).map(a => sourceNames(a.sources)).join(" "),
    tracked_servers: r => String(r.report?.servers?.length ?? 0),
    tracked_server_names: r => (r.report?.servers ?? []).map(s => String(s?.serverName ?? "")).join(" | "),
    reasons: r => {
        const out: string[] = [];
        for (const account of accountsOf(r)) {
            for (const [name, detail] of Object.entries(account.reasons ?? {})) {
                out.push(`${name}: ${flat((detail as any)?.message)}`);
            }
        }
        return out.join(" | ");
    },
    evidence: r => {
        const out: string[] = [];
        for (const account of accountsOf(r)) {
            for (const detail of Object.values(account.reasons ?? {})) {
                for (const item of ((detail as any)?.evidence ?? []) as unknown[]) out.push(flat(item));
            }
        }
        return out.join(" | ");
    },
    /**
     * A lookup that did not answer. Never blank-by-omission: an empty verdict
     * column with no error beside it would read as "checked, nothing found",
     * and an outage is not a clean result.
     */
    error: r => String(r.report?.error ?? ""),
};

/**
 * The sensible default set (rsb/export.py:104-116), plus `error`.
 *
 * The Python leaves the error column out of its default, which means a member
 * whose lookup failed exports as `UNKNOWN / Untracked` with nothing beside it
 * saying why — indistinguishable, in a spreadsheet, from a member Rotector
 * simply does not know. The plugin refuses that reading everywhere else (the
 * ledger prints "did not answer", the summary counts it separately), so the
 * column travels by default here too. It is empty for every row that answered.
 */
export const DEFAULT_COLUMNS: string[] = [
    "discord_id",
    "username",
    "display_name",
    "verdict",
    // On by default (rsb/export.py:127-129), because a stale finding that is
    // not labelled reads as a current one — and the cell is blank for every
    // finding inside the window, so it costs nothing in the ordinary case.
    "stale",
    "flag",
    "actionable",
    "category",
    "confidence",
    "roblox_accounts",
    "tracked_servers",
    "reasons",
    "error",
];

export const ALL_COLUMNS: string[] = Object.keys(COLUMNS);

/** Keep only columns that exist, preserving the caller's order. */
export function validColumns(names: Iterable<string> | null | undefined): string[] {
    const seen = new Set<string>();
    const out: string[] = [];
    for (const name of names ?? []) {
        const key = String(name);
        if (COLUMNS[key] && !seen.has(key)) {
            seen.add(key);
            out.push(key);
        }
    }
    return out.length ? out : [...DEFAULT_COLUMNS];
}

/** `discord_id` -> `Discord Id`, the label the TXT and HTML print. */
export function columnLabel(name: string): string {
    return String(name)
        .replace(/_/g, " ")
        .replace(/\b\w/g, c => c.toUpperCase());
}

export function cellValue(row: ExportRow, column: string): string {
    const read = COLUMNS[column];
    if (!read) return "";
    return safely(() => String(read(row) ?? ""), "");
}

// --------------------------------------------------------------------------
// palette — a port of rsb/palette.py
//
// The Python keeps colours as both hex strings and Pillow RGB tuples because
// Pillow cannot take a CSS colour. A canvas can, so everything here stays a CSS
// string and the tuple half of that module is simply not needed.
// --------------------------------------------------------------------------

export interface ExportPalette {
    /** the page or image background */
    background: string;
    /** cards, table headers, anything raised off the background */
    panel: string;
    /** alternating table rows */
    stripe: string;
    /** rules and borders */
    grid: string;
    /** the quieter rule the HTML uses between rows and card sections */
    rule: string;
    /** link text, which has to carry on the background rather than on the accent */
    link: string;
    /** whether this is a dark palette, for `color-scheme` and contrast picks */
    dark: boolean;
    /** body text */
    text: string;
    /** labels, captions, anything subordinate */
    muted: string;
    /** the export's title */
    heading: string;
    /** links, and the active state of a filter button */
    accent: string;
    /** text drawn *on* the accent */
    onAccent: string;
    /** verdict -> accent. Never themed. See `paletteFromTheme`. */
    verdicts: Record<number, string>;
    /** the name of the theme this came from, for the export's own footer */
    source: string;
}

/** verdict -> accent, the same five the terminal, the plugin and the page use */
export const DEFAULT_VERDICT_COLOURS: Record<number, string> = {
    [Verdict.THREAT]: "#f43f5e",
    [Verdict.CAUTION]: "#facc15",
    [Verdict.INFO]: "#38bdf8",
    [Verdict.NO_DETECTIONS]: "#4ade80",
    [Verdict.UNKNOWN]: "#8a929c",
};

/**
 * The fixed dark look exports have always had (rsb/palette.py:63-92).
 *
 * Deliberately *not* the plugin's own two-value language. An export is a file
 * that leaves the client and is read in a browser or an image viewer, and
 * style.css says as much where it notes that the HTML export's round avatar is
 * "the old export skin, not this language". Keeping the skin means an export
 * made by the plugin and one made by the terminal app are the same document.
 */
export const DEFAULT_PALETTE: ExportPalette = {
    background: "#121418",
    panel: "#1c2026",
    stripe: "#171a1f",
    grid: "#343a42",
    rule: "#23272e",
    link: "#7aa2f7",
    dark: true,
    text: "#dee2e6",
    muted: "#8a929c",
    heading: "#ffa62b",
    accent: "#2b62d9",
    onAccent: "#ffffff",
    verdicts: { ...DEFAULT_VERDICT_COLOURS },
    source: "",
};

/** The colour a verdict is drawn in. Falls back to body text, never to nothing. */
export function verdictColour(verdict: Verdict, palette?: ExportPalette | null): string {
    const source = palette ?? DEFAULT_PALETTE;
    return source.verdicts?.[verdict] ?? DEFAULT_VERDICT_COLOURS[verdict] ?? source.text;
}

/** `#rgb`, `#rrggbb`, `rgb()` and `rgba()` -> channels. Anything else is declined. */
export function parseColour(value: string | null | undefined): [number, number, number] | null {
    const text = String(value ?? "").trim();
    if (!text) return null;
    if (text.startsWith("#")) {
        const body = text.slice(1);
        if (body.length === 3 && /^[0-9a-f]{3}$/i.test(body)) {
            return [
                parseInt(body[0] + body[0], 16),
                parseInt(body[1] + body[1], 16),
                parseInt(body[2] + body[2], 16),
            ];
        }
        if (body.length === 6 && /^[0-9a-f]{6}$/i.test(body)) {
            return [
                parseInt(body.slice(0, 2), 16),
                parseInt(body.slice(2, 4), 16),
                parseInt(body.slice(4, 6), 16),
            ];
        }
        return null;
    }
    const match = /^rgba?\(\s*([\d.]+)[\s,]+([\d.]+)[\s,]+([\d.]+)/i.exec(text);
    if (!match) return null;
    const channels = [Number(match[1]), Number(match[2]), Number(match[3])];
    if (channels.some(c => !isFinite(c))) return null;
    return [
        Math.max(0, Math.min(255, Math.round(channels[0]))),
        Math.max(0, Math.min(255, Math.round(channels[1]))),
        Math.max(0, Math.min(255, Math.round(channels[2]))),
    ];
}

/**
 * The colour that means "this variable did not answer".
 *
 * A value no theme would ever set deliberately, used both as the `var()`
 * fallback and as the probe's inherited colour, so an undefined variable and
 * one that is invalid at computed-value time both land on the same reading.
 */
const SENTINEL = "rgb(1, 2, 3)";

/** 0 (black) to 1 (white). Used only to decide whether a resolved theme is dark. */
function luminance(value: string): number {
    const rgb = parseColour(value);
    if (!rgb) return 0;
    return (0.2126 * rgb[0] + 0.7152 * rgb[1] + 0.0722 * rgb[2]) / 255;
}

/**
 * Resolve a chain of Discord custom properties to a real colour.
 *
 * `getComputedStyle(root).getPropertyValue("--background-primary")` is not
 * enough: a custom property's value is substituted only where it is *used*, so
 * on a current client that call hands back the literal text
 * `hsl(var(--primary-630-hsl))`. Setting the chain as an element's `color` and
 * reading the computed value back makes the browser do the substitution, which
 * is why this goes through a probe node rather than reading the variable.
 *
 * This is the one place the port diverges from `palette._hex`, which declines
 * anything that is not a hex triple because Textual answers `auto 87%` for
 * several variables. A browser answers a resolved `rgb(...)`, which *is* a
 * colour, so it is accepted and used as-is.
 */
function resolveVar(probe: HTMLElement | null, names: string[], fallback: string): string {
    if (!probe) return fallback;
    for (const name of names) {
        try {
            probe.style.color = "";
            probe.style.color = `var(${name}, ${SENTINEL})`;
            if (!probe.style.color) continue;
            const computed = String(window.getComputedStyle(probe).color ?? "");
            const parsed = parseColour(computed);
            if (!parsed) continue;
            // The sentinel means the variable did not answer — either it is not
            // defined, and the fallback inside var() was used, or it is defined
            // as something that is invalid at computed-value time, in which case
            // `color` falls back to the inherited value, which the wrapper sets
            // to the same sentinel. Either way there is nothing to take.
            if (parsed[0] === 1 && parsed[1] === 2 && parsed[2] === 3) continue;
            return `rgb(${parsed[0]}, ${parsed[1]}, ${parsed[2]})`;
        } catch {
            // a hostile or missing document; the fallback is the answer
        }
    }
    return fallback;
}

/**
 * A palette built from the client's own theme, for `exportFollowTheme`.
 *
 * The port of `palette.from_theme`, and its central rule survives verbatim:
 * **verdict colours are not taken from the theme.** They are the export's
 * evidence — a THREAT row is red because it is a threat — and a client running
 * a monochrome theme would otherwise drain exactly the distinction a reader
 * scans for. The chrome follows the app; the findings keep their meaning.
 *
 * Both variable families are asked for in turn because Discord is mid-migration
 * and a given build may define either.
 */
export function paletteFromTheme(): ExportPalette {
    let holder: HTMLElement | null = null;
    let probe: HTMLElement | null = null;
    try {
        holder = document.createElement("div");
        holder.setAttribute("aria-hidden", "true");
        holder.style.position = "absolute";
        holder.style.opacity = "0";
        holder.style.pointerEvents = "none";
        // the inherited colour the probe falls back to when a variable does not
        // resolve; see `resolveVar`
        holder.style.color = SENTINEL;
        probe = document.createElement("span");
        holder.appendChild(probe);
        document.body.appendChild(holder);
    } catch {
        holder = null;
        probe = null;
    }

    try {
        // Nothing to read the theme out of. Saying so by returning the fixed
        // palette is better than returning the fixed palette with a footer
        // claiming it followed a theme it never saw.
        if (!probe) return DEFAULT_PALETTE;

        const background = resolveVar(probe, ["--background-base-lower", "--background-primary"], DEFAULT_PALETTE.background);
        const dark = luminance(background) < 0.5;
        const panel = resolveVar(probe, ["--background-base-low", "--background-secondary"], DEFAULT_PALETTE.panel);
        const text = resolveVar(probe, ["--text-default", "--text-normal"], DEFAULT_PALETTE.text);
        const accent = resolveVar(probe, ["--brand-500", "--brand-experiment"], DEFAULT_PALETTE.accent);
        return {
            background,
            panel,
            stripe: resolveVar(probe, ["--background-base-lowest", "--background-secondary-alt"], panel),
            grid: resolveVar(probe, ["--border-strong", "--background-modifier-accent"], dark ? DEFAULT_PALETTE.grid : "#c8ccd2"),
            rule: resolveVar(probe, ["--border-subtle", "--background-modifier-accent"], dark ? DEFAULT_PALETTE.rule : "#dfe3e8"),
            link: resolveVar(probe, ["--text-link", "--text-brand"], DEFAULT_PALETTE.link),
            dark,
            text,
            muted: resolveVar(probe, ["--text-muted", "--text-secondary"], DEFAULT_PALETTE.muted),
            heading: text,
            accent,
            onAccent: resolveVar(probe, ["--white-500", "--white"], DEFAULT_PALETTE.onAccent),
            // the one thing the theme may not touch
            verdicts: { ...DEFAULT_VERDICT_COLOURS },
            source: "the Discord client's theme",
        };
    } catch (err) {
        logger.error("could not read the client theme; using the default export palette", err);
        return DEFAULT_PALETTE;
    } finally {
        try {
            holder?.remove();
        } catch {
            // nothing to clean up
        }
    }
}

/** Read one plugin setting. `settings.store` throws before registration. */
function setting<T>(key: string, fallback: T): T {
    return safely(() => {
        const store = (settings as any)?.store;
        if (store == null) return fallback;
        const value = store[key];
        return value === undefined || value === null ? fallback : (value as T);
    }, fallback);
}

/**
 * The palette an export is drawn in.
 *
 * Off by default: the fixed dark skin is what the terminal app produces, so two
 * exports of the same scan from two machines are the same document. Switching
 * `exportFollowTheme` on makes the chrome follow the client, which is what
 * `[export] follow_theme` does in the Python.
 */
export function resolvePalette(): ExportPalette {
    if (!setting("exportFollowTheme", false)) return DEFAULT_PALETTE;
    return paletteFromTheme();
}

// --------------------------------------------------------------------------
// retention — what is true of *this* file
//
// An exported file outlives everything the plugin can sweep: nothing expires a
// CSV sitting in somebody's downloads folder. So the file says what its own
// retention is, and it says it from the setting that was actually in force when
// it was written rather than from the rule in the abstract. Both readings are
// overridable through ExportOptions so a caller that already knows (a stored
// scan being re-exported, a test) can state the truth about that run instead of
// about this moment.
// --------------------------------------------------------------------------

/** Whether this run was told to keep findings past the terms' 24-hour window. */
export function retainedBeyondTerms(opts?: ExportOptions | null): boolean {
    if (typeof opts?.retainBeyondTerms === "boolean") return opts.retainBeyondTerms;
    return safely(() => retainBeyondTermsFrom((settings as any)?.store), false);
}

/**
 * How many hours this file is claiming for itself.
 *
 * The terms' 24 unless the ceiling has been lifted, in which case it is the
 * configured window — the number the caches are actually holding to, so the
 * file's expiry line and the plugin's own sweep cannot disagree.
 */
export function retentionWindowHours(opts?: ExportOptions | null): number {
    if (!retainedBeyondTerms(opts)) return RETENTION_HOURS;
    const asked = Number(opts?.retentionHours);
    if (isFinite(asked) && asked >= 1) return Math.floor(asked);
    return safely(() => retentionHoursFrom((settings as any)?.store), RETENTION_HOURS);
}

/**
 * How many of these findings were already past the 24-hour window.
 *
 * Independent of any setting, exactly as rsb/export.py:229 has it: results left
 * on a screen for two days are as stale as ones served from a cache that was
 * told to keep them, and a file is entitled to say so either way.
 */
export function countStale(rows: ExportRow[]): number {
    let stale = 0;
    for (const row of rows ?? []) {
        if (safely(() => isStale(row?.report), false)) stale++;
    }
    return stale;
}

// --------------------------------------------------------------------------
// stamps, names and the header every file carries
// --------------------------------------------------------------------------

function pad(value: number, width = 2): string {
    return String(Math.trunc(Math.abs(value))).padStart(width, "0");
}

/** `20260816T215249Z` — the stamp the folder name and every header carry. */
export function timestamp(now: Date = new Date()): string {
    const d = isFinite(now?.getTime?.()) ? now : new Date();
    return (
        `${d.getUTCFullYear()}${pad(d.getUTCMonth() + 1)}${pad(d.getUTCDate())}` +
        `T${pad(d.getUTCHours())}${pad(d.getUTCMinutes())}${pad(d.getUTCSeconds())}Z`
    );
}

function parseStamp(stamp: string): Date | null {
    const m = /^(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})(\d{2})Z$/.exec(String(stamp ?? ""));
    if (!m) return null;
    const ms = Date.UTC(+m[1], +m[2] - 1, +m[3], +m[4], +m[5], +m[6]);
    return isFinite(ms) ? new Date(ms) : null;
}

/**
 * `2026-08-17 21:52 UTC` — when the file must be gone by.
 *
 * `hours` defaults to the terms' window, which is the answer in the default
 * state and the one every existing caller wants. A run with the ceiling lifted
 * passes its own window, because a file whose README says it is being kept for
 * a week must not print a deadline from yesterday.
 */
export function expiryText(stamp: string, hours: number = RETENTION_HOURS): string {
    const at = parseStamp(stamp) ?? new Date();
    const window = isFinite(Number(hours)) && Number(hours) > 0 ? Number(hours) : RETENTION_HOURS;
    const gone = new Date(at.getTime() + window * 3600 * 1000);
    return (
        `${gone.getUTCFullYear()}-${pad(gone.getUTCMonth() + 1)}-${pad(gone.getUTCDate())} ` +
        `${pad(gone.getUTCHours())}:${pad(gone.getUTCMinutes())} UTC`
    );
}

/** `My Server` + stamp -> `My-Server-20260816T215249Z`, safe on every filesystem. */
export function exportStem(label: string, stamp: string): string {
    const safe = String(label ?? "")
        .split("")
        .map(c => (/[A-Za-z0-9\-_]/.test(c) ? c : "-"))
        .join("")
        .slice(0, 40)
        .replace(/^-+|-+$/g, "");
    return `${safe || "rotector-scan"}-${stamp}`;
}

/** `stem.part02-of-11.csv`, or just `stem.csv` when there is only one. */
export function segmentName(stem: string, index: number, total: number, ext: string): string {
    if (total <= 1) return `${stem}.${ext}`;
    const width = String(total).length;
    return `${stem}.part${String(index).padStart(width, "0")}-of-${total}.${ext}`;
}

export interface ExportOptions {
    /** what was scanned: this server, a role, the friends list. Titles every file. */
    label?: string;
    /** "filtered" or "all" — printed, never inferred by the reader */
    scope?: string;
    columns?: string[];
    segmentSize?: number;
    /** the one stamp every file in a single export shares */
    stamp?: string;
    guildId?: string;
    palette?: ExportPalette | null;
    /** how many members were scanned, when more were scanned than are listed */
    scanned?: number;
    /** the coverage sentence from members.ts, carried into the file verbatim */
    note?: string;
    /**
     * Whether this run kept findings past the terms' window. Defaults to the
     * live setting; pass it when the caller knows better than "now" does.
     */
    retainBeyondTerms?: boolean;
    /** the window that was actually in force, in hours. Only read when the above is true. */
    retentionHours?: number;
}

/**
 * The six lines every file leads with (rsb/export.py:238-283).
 *
 * `Expires` and `Source` are the two the terms require. The others are what
 * makes the file readable a week later, when nobody remembers which server it
 * was.
 *
 * The expiry line states what is true of *this* file. With retention past the
 * terms switched on, repeating "delete within 24 hours" would be describing a
 * rule the run did not follow — so the line says how long the file is being
 * kept and what the terms allow instead, and still names them, because whoever
 * opens the file did not make that choice. `Retained` and `Stale` appear only
 * in that state and only when there is something to report, so a default export
 * reads exactly as it always has.
 */
export function headerLines(rows: ExportRow[], opts: ExportOptions): string[] {
    const stamp = opts.stamp || timestamp();
    const retained = retainedBeyondTerms(opts);
    const hours = retentionWindowHours(opts);
    const stale = countStale(rows);

    const lines = [
        `Scan:      ${opts.label || "members"}`,
        `Generated: ${stamp}`,
        `Scope:     ${opts.scope || "filtered"}`,
        `Members:   ${rows.length}`,
    ];
    if (typeof opts.scanned === "number" && opts.scanned > rows.length) {
        lines.push(`Scanned:   ${opts.scanned} (${opts.scanned - rows.length} not listed under this scope)`);
    }
    if (retained) {
        lines.push(
            `Expires:   ${expiryText(stamp, hours)} - kept ${hours}h by the operator's choice; ` +
            `Rotector's Terms of Use allow ${RETENTION_HOURS}h`,
            "Retained:  beyond the terms - retain_beyond_terms was on when this was written"
        );
    } else {
        lines.push(`Expires:   ${expiryText(stamp)} - Rotector's Terms of Use forbid keeping this longer`);
    }
    if (stale) {
        lines.push(
            `Stale:     ${stale} of ${rows.length} finding(s) were already older than ` +
            `${RETENTION_HOURS} hours when this was written - see the Stale column, and re-check before acting`
        );
    }
    lines.push(
        `Source:    ${ATTRIBUTION}`,
        `Appeals:   ${APPEAL_URL}`
    );
    if (opts.note) lines.push(`Coverage:  ${opts.note}`);
    return lines;
}

/**
 * The closing paragraph about this file's own retention.
 *
 * The lifted case is not "delete within 24 hours" with a softer verb: this run
 * was told to keep the data longer, and printing the rule it did not follow
 * would be theatre. The terms are named either way, and so is what the age
 * means for the findings.
 *
 * `whenInsideTerms` is the caller's own default-state wording, passed in rather
 * than shared, because the TXT and the README wrap that paragraph differently
 * and neither of them may change while the setting is off — a file produced in
 * the default state must read exactly as it always has, to the byte.
 */
export function retentionNoteLines(
    rows: ExportRow[],
    opts: ExportOptions,
    whenInsideTerms: string[]
): string[] {
    const retained = retainedBeyondTerms(opts);
    const hours = retentionWindowHours(opts);
    const stale = countStale(rows);

    const lines = retained
        ? [
            `This export is being kept for ${hours} hours by choice.`,
            `Rotector's Terms of Use allow ${RETENTION_HOURS} hours, and flag`,
            "statuses change well inside that: anything here older than a day",
            "describes the day it was answered rather than today. Anyone listed",
            `can appeal at ${APPEAL_URL}`,
        ]
        : [...whenInsideTerms];

    if (stale) {
        lines.push(
            "",
            `${stale} of the ${rows.length} finding(s) here were already older than ${RETENTION_HOURS} hours`,
            "when this was written; each one's age is in the Stale column. Re-check",
            "before acting on those."
        );
    }
    return lines;
}

/**
 * What each verdict in this file actually means.
 *
 * The plugin's rule is that a verdict word never travels without its meaning,
 * and a column of bare words in a spreadsheet is precisely where "NO
 * DETECTIONS" gets read as "cleared". Printing the legend once per file, for
 * the verdicts that are actually present, keeps that sentence attached without
 * repeating seventy characters on every row.
 */
export function verdictLegend(rows: ExportRow[]): string[] {
    const present = new Set<Verdict>();
    for (const row of rows) present.add(rowVerdict(row));
    const lines: string[] = [];
    for (const verdict of [...ALL_VERDICTS].reverse()) {
        if (!present.has(verdict)) continue;
        lines.push(`${verdictLabel(verdict)}: ${verdictMeaning(verdict)}`);
    }
    return lines;
}

// --------------------------------------------------------------------------
// CSV
// --------------------------------------------------------------------------

/**
 * One CSV field.
 *
 * RFC 4180 quoting, plus one guard the Python does not need: a leading `=`,
 * `+`, `-`, `@`, tab or carriage return makes a spreadsheet treat the cell as a
 * formula, and every free-text column here is third-party text — Roblox
 * usernames, detector messages, evidence. A finding must not be able to run
 * anything when a moderator opens the file, so those cells are prefixed with an
 * apostrophe, which spreadsheets read as "this is text".
 */
function csvField(value: string): string {
    let text = String(value ?? "");
    if (/^[=+\-@\t\r]/.test(text)) text = `'${text}`;
    if (/[",\r\n]/.test(text)) return `"${text.replace(/"/g, '""')}"`;
    return text;
}

function csvRow(values: string[]): string {
    return values.map(csvField).join(",");
}

/**
 * CSV, split into numbered segments when the list is long.
 *
 * Each part is a complete CSV with its own comment header and its own column
 * row, so every segment opens on its own — which is the whole point of
 * segmenting rather than truncating.
 *
 * The header lines are `#`-prefixed comments rather than a sidecar README,
 * because a browser hands over one file at a time and there is no folder to put
 * a README in. A spreadsheet shows them as a few rows of text above the table;
 * that is the price of the attribution and the expiry travelling with the data,
 * and the terms do not make it optional.
 */
export function exportCsv(reports: ExportInput, opts: ExportOptions = {}): string[] {
    const rows = asRows(reports);
    const columns = validColumns(opts.columns);
    const size = Math.max(0, Math.trunc(Number(opts.segmentSize ?? DEFAULT_SEGMENT_SIZE)) || 0);

    const chunks: ExportRow[][] = [];
    if (size > 0 && rows.length > size) {
        for (let i = 0; i < rows.length; i += size) chunks.push(rows.slice(i, i + size));
    } else {
        chunks.push(rows);
    }

    const notice = [
        ...headerLines(rows, opts),
        ...verdictLegend(rows),
    ];

    return chunks.map((chunk, index) => {
        const lines: string[] = [];
        for (const line of notice) lines.push(`# ${line}`);
        if (chunks.length > 1) lines.push(`# Part:      ${index + 1} of ${chunks.length}`);
        lines.push(csvRow(columns));
        for (const row of chunk) lines.push(csvRow(columns.map(column => cellValue(row, column))));
        // a trailing newline, so a shell that concatenates parts does not join
        // the last row of one to the header comment of the next
        return `${lines.join("\r\n")}\r\n`;
    });
}

// --------------------------------------------------------------------------
// TXT
// --------------------------------------------------------------------------

/** A readable report — one block per member, not a table (rsb/export.py:268-309). */
export function exportTxt(reports: ExportInput, opts: ExportOptions = {}): string {
    const rows = asRows(reports);
    const columns = validColumns(opts.columns);
    const labels: Record<string, string> = {};
    let pad = 0;
    for (const column of columns) {
        labels[column] = columnLabel(column);
        pad = Math.max(pad, labels[column].length);
    }

    const header = headerLines(rows, opts);
    const legend = verdictLegend(rows);
    const rule = "=".repeat(Math.max(1, ...header.map(h => h.length)));

    const lines: string[] = [rule, ...header, rule, ""];
    if (legend.length) {
        lines.push("What the verdicts mean:");
        for (const line of legend) lines.push(`  ${line}`);
        lines.push("");
    }

    rows.forEach((row, index) => {
        let title = `${index + 1}. ${row.displayName}`;
        if (row.username && row.username !== row.displayName) title += ` (@${row.username})`;
        lines.push(title);
        lines.push("-".repeat(title.length));
        // Spelled out per member rather than left to the Stale column, which
        // the operator can deselect: whether this block is a claim about today
        // is not a formatting preference (rsb/export.py:371-374).
        const note = safely(() => staleNote(row.report), "");
        if (note) lines.push(`  ${note}`);
        for (const column of columns) {
            const value = cellValue(row, column);
            if (!value) continue;
            lines.push(`  ${labels[column].padEnd(pad)}  ${value}`);
        }
        lines.push("");
    });

    if (!rows.length) {
        lines.push("(no members matched the selected filter)");
        lines.push("");
    }

    lines.push(
        ...retentionNoteLines(rows, opts, [
            `Delete this file within ${RETENTION_HOURS} hours. Rotector flag statuses change, and`,
            "their Terms of Use forbid retaining responses beyond that.",
            `Anyone listed here can appeal at ${APPEAL_URL}`,
        ]),
        "",
        MARKER,
        ""
    );
    return lines.join("\n");
}

// --------------------------------------------------------------------------
// JSON
// --------------------------------------------------------------------------

export function exportJson(reports: ExportInput, opts: ExportOptions = {}): string {
    const rows = asRows(reports);
    const columns = validColumns(opts.columns);
    const stamp = opts.stamp || timestamp();

    const meanings: Record<string, string> = {};
    for (const verdict of ALL_VERDICTS) meanings[verdictName(verdict)] = verdictMeaning(verdict);

    const retained = retainedBeyondTerms(opts);
    const hours = retentionWindowHours(opts);
    const stale = countStale(rows);

    const payload = {
        scan: { label: opts.label || "members", guildId: opts.guildId || "" },
        generated_at: stamp,
        scope: opts.scope || "filtered",
        // What is true of this file, not the rule in the abstract: repeating
        // the 24-hour line over data deliberately kept longer would be a claim
        // the run did not honour. The terms are named either way.
        expires_at: retained
            ? `${expiryText(stamp, hours)} (${hours} hours after generated_at - kept past the ` +
              `${RETENTION_HOURS} hours Rotector's Terms of Use #1 allow, by the operator's choice)`
            : `${expiryText(stamp)} (${RETENTION_HOURS} hours after generated_at, Rotector Terms of Use #1)`,
        retained_beyond_terms: Boolean(retained),
        stale_findings: stale,
        stale_note: stale
            ? `${stale} finding(s) here are older than ${RETENTION_HOURS} hours. Flag types change ` +
              "and appeals succeed, so those describe the day they were answered, not today - " +
              "re-check before acting. Per-member ages are in the 'stale' column."
            : "",
        attribution: ATTRIBUTION,
        appeals: APPEAL_URL,
        coverage: opts.note || "",
        verdict_meanings: meanings,
        columns: [...columns],
        members: rows.map(row => {
            const record: Record<string, string> = {};
            for (const column of columns) record[column] = cellValue(row, column);
            return record;
        }),
    };
    return `${JSON.stringify(payload, null, 2)}\n`;
}

// --------------------------------------------------------------------------
// the README that travels with an export
// --------------------------------------------------------------------------

/**
 * The plain-text note the Python writes beside the files.
 *
 * The terminal app can enforce the retention window — `purge_expired` deletes
 * its own folders on the next export. A renderer cannot delete a file it has
 * handed to the download manager, so this note, and the header inside every
 * file, are the whole of the enforcement. That is why it is offered alongside
 * every export rather than as an option.
 */
export function exportReadme(reports: ExportInput, opts: ExportOptions & { files?: string[]; } = {}): string {
    const rows = asRows(reports);
    const legend = verdictLegend(rows);
    const lines = [...headerLines(rows, opts), ""];
    if (opts.files?.length) {
        lines.push("Files:");
        for (const file of opts.files) lines.push(`  ${file}`);
        lines.push("");
    }
    if (legend.length) {
        lines.push("What the verdicts mean:");
        for (const line of legend) lines.push(`  ${line}`);
        lines.push("");
    }
    lines.push(
        "NO DETECTIONS means nothing has been detected yet. It is not a clean bill",
        "of health and it is never a background check.",
        "",
        ...retentionNoteLines(rows, opts, [
            `Delete these files within ${RETENTION_HOURS} hours. Rotector flag statuses change,`,
            "and their Terms of Use forbid retaining responses beyond that. Anyone",
            `listed here can appeal at ${APPEAL_URL}`,
        ]),
        "",
        MARKER,
        ""
    );
    return lines.join("\n");
}

// --------------------------------------------------------------------------
// delivery
// --------------------------------------------------------------------------

export function formatExtension(format: string): string {
    return format === "json" ? "json" : format === "html" ? "html" : format === "png" ? "png" : format === "txt" ? "txt" : "csv";
}

export function formatMime(format: string): string {
    switch (format) {
        case "json": return "application/json;charset=utf-8";
        case "html": return "text/html;charset=utf-8";
        case "png": return "image/png";
        case "txt": return "text/plain;charset=utf-8";
        default: return "text/csv;charset=utf-8";
    }
}

/**
 * Hand one file to the user.
 *
 * A blob URL and a programmatic `<a download>`, which is the only route a
 * renderer has: the plugin has no `native.ts`, so it cannot write to disk, and
 * everything it could write would be Rotector's data sitting somewhere nothing
 * sweeps.
 *
 * The URL is revoked afterwards rather than immediately. Revoking in the same
 * tick can cancel the download before Chromium has taken its own reference to
 * the blob; the delay is long enough for the download to have started and short
 * enough that a 20 MB image is not held for the rest of the session.
 */
export function download(name: string, data: Blob | string, mime = "text/plain;charset=utf-8"): void {
    let url = "";
    try {
        const blob = typeof data === "string"
            // The BOM is for Excel, which otherwise reads a UTF-8 CSV as the
            // system codepage and mangles every non-ASCII username in it.
            ? new Blob([mime.startsWith("text/csv") ? `\uFEFF${data}` : data], { type: mime })
            : data;
        url = URL.createObjectURL(blob);

        const anchor = document.createElement("a");
        anchor.href = url;
        anchor.download = String(name || "rotector-export");
        anchor.rel = "noopener";
        anchor.style.display = "none";
        document.body.appendChild(anchor);
        anchor.click();
        anchor.remove();
    } catch (err) {
        logger.error(`could not deliver ${name}`, err);
    } finally {
        if (url) {
            setTimeout(() => {
                try {
                    URL.revokeObjectURL(url);
                } catch {
                    // already gone
                }
            }, 10_000);
        }
    }
}

export interface DownloadFile {
    name: string;
    data: Blob | string;
    mime: string;
}

/**
 * Hand over several files, spaced out.
 *
 * Chromium drops downloads that arrive in the same burst from one gesture, and
 * a segmented export is exactly that burst — so an export of eleven CSV parts
 * would silently deliver two of them. The gap is small enough not to be felt
 * and large enough that each click is its own download.
 */
export async function downloadAll(files: DownloadFile[]): Promise<number> {
    let delivered = 0;
    for (const file of files ?? []) {
        if (!file) continue;
        download(file.name, file.data, file.mime);
        delivered++;
        await new Promise(resolve => setTimeout(resolve, 220));
    }
    return delivered;
}
