"""Export a running Textual app as an SVG dressed like the project page.

Rich's default SVG export wraps the terminal in macOS window chrome -- rounded
corners, three coloured traffic lights, a grey ground. Dropped into
``docs/index.html`` that reads as a *picture of a terminal on someone's desktop*
sitting on a page whose own rule is a hairline rectangle with zero radius and
exactly two values.

So the chrome here is the page's Data Node instead: a 1px rule frame, an
uppercase tracked label, and a barcode chip that eats the rest of the header
width. Same component the page draws around its other evidence.

What is *inside* the frame stays the program. Verdict colour survives at full
strength, because the app spends it on meaning -- a THREAT row is red because
it is a threat. The page's own note is that colour appears there only inside
these screenshots, and that stays true: the chrome lost its colour, the
evidence kept it.

Text is positioned by ``textLength`` on every run, so glyphs land on the right
cells whatever font the viewer actually resolves. That matters because an SVG
loaded through ``<img>`` cannot fetch a webfont: the family below is a request,
not a guarantee, and the layout does not depend on it being honoured.
"""
from __future__ import annotations

import io
from math import ceil
from pathlib import Path

from rich.console import Console
from rich.terminal_theme import TerminalTheme

from rsb.tui.theme import (
    CAUTION,
    CLEAR,
    GROUND,
    INK,
    NOTE,
    RULE,
    THREAT,
    NAME as THEME_NAME,
)

#: Azeret Mono's advance is 0.65 em against Fira Code's 0.61. Rich sizes the
#: character cell from this, so passing the real ratio keeps a cell the shape of
#: the glyph the page asks for rather than a narrower one it has to squeeze.
FONT_ASPECT = 0.65

FONT_STACK = (
    '"Azeret Mono", ui-monospace, SFMono-Regular, Menlo, Consolas, monospace'
)


def _rgb(value: str) -> tuple[int, int, int]:
    value = value.lstrip("#")
    return (int(value[0:2], 16), int(value[2:4], 16), int(value[4:6], 16))


#: black, red, green, yellow, blue, magenta, cyan, white. Textual has usually
#: resolved its own colours to truecolor long before Rich sees them, so this
#: mostly governs the default fore/background -- but where a bare ANSI colour
#: does reach the exporter, it should land on the same hue the app would have
#: drawn rather than on Rich's default palette.
_NORMAL = [
    _rgb(GROUND), _rgb(THREAT), _rgb(CLEAR), _rgb(CAUTION),
    _rgb("#5b8dee"), _rgb("#c678dd"), _rgb(NOTE), _rgb("#c4c4c4"),
]
_BRIGHT = [
    _rgb("#3a3a3a"), _rgb("#ff6b6b"), _rgb("#5ee08c"), _rgb("#ffc94d"),
    _rgb("#84aef5"), _rgb("#d99ae8"), _rgb("#87e5f5"), _rgb(INK),
]

SITE_TERMINAL = TerminalTheme(_rgb(GROUND), _rgb(INK), _NORMAL, _BRIGHT)

#: the page's own divider: a 24px period with bars at 0-1, 3-4, 9-11, 14-15 and
#: 21-22, which is the gradient `.bars` paints in the stylesheet
_BAR_PERIOD = 24
_BARS = ((0, 1), (3, 1), (9, 2), (14, 1), (21, 1))

#: Rich fixes its own geometry: a 1px margin plus 8px side padding, and 40px of
#: top padding. That 40px band is what the node header gets to live in.
_MARGIN = 1
_PAD = 8
_HEADER_H = _MARGIN + 40
_EDGE = _MARGIN + _PAD

_LABEL_SIZE = 11
_CHIP_H = 10


def _svg_width(columns: int) -> int:
    """The width Rich will give the finished SVG, computed the way Rich does."""
    char_width = 20 * FONT_ASPECT
    return ceil(columns * char_width + _PAD * 2) + _MARGIN * 2


def _format(label: str, svg_width: int) -> str:
    """Build the SVG template for one screenshot's header label.

    Only the chip needs a real number: everything else is either a constant of
    Rich's geometry or a percentage, so the template does not have to guess at
    the height, which depends on how many lines the app drew.
    """
    bars = "".join(
        f'<rect x="{x}" y="0" width="{w}" height="{_CHIP_H}" fill="{INK}"/>'
        for x, w in _BARS
    )
    # tracked uppercase: a cell is the glyph advance plus the 0.19em tracking
    chip_x = _EDGE + ceil(len(label) * (_LABEL_SIZE * FONT_ASPECT + _LABEL_SIZE * 0.19)) + 16
    chip_w = max(0, svg_width - chip_x - _EDGE)

    return f"""<svg class="rich-terminal" viewBox="0 0 {{width}} {{height}}" xmlns="http://www.w3.org/2000/svg">
    <!-- Generated by tools/screenshots.py: a real render of the program, in the
         page's own frame. Regenerate rather than edit. -->
    <style>
    .{{unique_id}}-matrix {{{{
        font-family: {FONT_STACK};
        font-size: {{char_height}}px;
        line-height: {{line_height}}px;
        font-variant-ligatures: none;
        font-variant-east-asian: full-width;
    }}}}
    .{{unique_id}}-label {{{{
        font-family: {FONT_STACK};
        font-size: {_LABEL_SIZE}px;
        font-weight: 500;
        letter-spacing: 0.19em;
    }}}}
    {{styles}}
    </style>

    <defs>
    <clipPath id="{{unique_id}}-clip-terminal">
      <rect x="0" y="0" width="{{terminal_width}}" height="{{terminal_height}}" />
    </clipPath>
    <pattern id="{{unique_id}}-bars" width="{_BAR_PERIOD}" height="{_CHIP_H}"
             patternUnits="userSpaceOnUse">{bars}</pattern>
    {{lines}}
    </defs>

    <rect x="0" y="0" width="100%" height="100%" fill="{GROUND}"/>
    <text class="{{unique_id}}-label" x="{_EDGE}" y="26" fill="{INK}">{label}</text>
    <rect x="{chip_x}" y="16" width="{chip_w}" height="{_CHIP_H}"
          fill="url(#{{unique_id}}-bars)" opacity="0.5"/>
    <rect x="0" y="{_HEADER_H - 1}" width="100%" height="1" fill="{RULE}"/>

    <g transform="translate({{terminal_x}}, {{terminal_y}})" clip-path="url(#{{unique_id}}-clip-terminal)">
    {{backgrounds}}
    <g class="{{unique_id}}-matrix">
    {{matrix}}
    </g>
    </g>

    <!-- last, so the frame sits over the matrix rather than under it. Stroked
         at 2 on the viewBox edge: the outer half clips away and leaves the
         hairline, which saves knowing the height. -->
    <rect x="0" y="0" width="100%" height="100%" fill="none"
          stroke="{RULE}" stroke-width="2"/>
</svg>
"""


def save(app, path: Path, label: str) -> None:
    """Write ``app``'s current screen to ``path`` as a page-framed SVG.

    Mirrors ``App.export_screenshot``, which offers no way to pass a terminal
    theme or a template, so the compositor call below is the one it makes.
    """
    if app.theme != THEME_NAME:
        raise RuntimeError(
            f"the page's screenshots are taken under the {THEME_NAME!r} theme; "
            f"this app is wearing {app.theme!r}"
        )

    columns, rows = app.size
    console = Console(
        width=columns,
        height=rows,
        file=io.StringIO(),
        force_terminal=True,
        color_system="truecolor",
        record=True,
        legacy_windows=False,
        safe_box=False,
    )
    console.print(
        app.screen._compositor.render_update(
            full=True, screen_stack=app._background_screens, simplify=False
        )
    )
    path.write_text(
        console.export_svg(
            title="",
            theme=SITE_TERMINAL,
            code_format=_format(label, _svg_width(columns)),
            font_aspect_ratio=FONT_ASPECT,
            unique_id=f"rsb-{path.stem}",
        ),
        encoding="utf-8",
    )


__all__ = ["save", "SITE_TERMINAL", "FONT_ASPECT", "FONT_STACK"]
